# Generated by Django 4.0.5 on 2022-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='imagen',
            field=models.ImageField(null=True, upload_to='sucursales'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='vehiculos'),
        ),
    ]
